version: "3.7"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    ports:
      - 5000:5000
    volumes:
      - db-data1:/sqlite

  scrape_worker:
    build:
      context: .
      dockerfile: Dockerfile.scrape_worker
    restart: always
    volumes:
      - db-data1:/sqlite

volumes:
  db-data1: